name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/control-api/requirements.txt
      - name: Build Docker images
        run: |
          docker build -t control-api:latest -f apps/control-api/Dockerfile apps/control-api/
          # Add for Flink jobs
          docker build -t stream-processor:latest -f apps/flink-jobs/stream-processor/Dockerfile apps/flink-jobs/stream-processor/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: pytest apps/control-api/tests/unit/
      - name: Run integration tests
        run: pytest apps/control-api/tests/integration/

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          namespace: telemetry
          images: |
            control-api:latest
            stream-processor:latest